# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 
    url: ''
    weight: 10
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  - name: News
    url: '#news'
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Talks
    url: '#talks'
    weight: 40
  - name: Projects
    url: '#projects'
    weight: 50
  - name: Students
    # url: ''
    weight: 50
  - name: List of Students
    url: 'students/students-list'
    weight: 10
    parent: Students
  - name: Assignments Proposals
    url: 'students/assignments-proposals'
    weight: 20
    parent: Students
  - name: Contact
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
